/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login LDAP corporativo
         * @description Autentica usuario contra Active Directory (`red.ecopetrol.com.co`). En caso de éxito establece cookie `prodia_session` (HttpOnly, SameSite=Lax) y registra evento `login` en `auth_events`. El token también se devuelve en el cuerpo para clientes sin soporte de cookies.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cerrar sesión
         * @description Elimina la cookie `prodia_session` del cliente y registra evento `logout` en `auth_events`. Requiere cookie de sesión válida.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sesión actual
         * @description Retorna el usuario autenticado y sus permisos efectivos (campos + secciones). Los permisos son la unión de los del grupo más los individuales. El header `X-Session-Expires` indica cuándo expira la sesión (ISO UTC).
         */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session-timeout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Timeout de sesión vigente (solo lectura)
         * @description Minutos de inactividad antes de que la sesión expire. Requiere sesión válida — lo consume el modal de inactividad del frontend. Editar el valor queda para el panel de administración (fuera de F0).
         */
        get: operations["session_timeout_api_v1_auth_session_timeout_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/permissions/my-permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Mis permisos
         * @description Retorna campos y secciones autorizadas del usuario autenticado.
         */
        get: operations["my_permissions_api_v1_permissions_my_permissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LoginRequest
         * @example {
         *       "password": "mi_clave_ad",
         *       "username": "jguerrero"
         *     }
         */
        LoginRequest: {
            /**
             * Username
             * @description Usuario de red sin dominio (ej: jguerrero, no jguerrero@ecopetrol.com.co)
             * @example jguerrero
             */
            username: string;
            /**
             * Password
             * @description Contraseña de directorio activo corporativo
             * @example ••••••••
             */
            password: string;
        };
        /**
         * LoginResponse
         * @example {
         *       "access_token": "InVzZXJfaWQiOiAxfQ.ZkV4Sg.abc123",
         *       "token_type": "bearer"
         *     }
         */
        LoginResponse: {
            /**
             * Access Token
             * @description Token de sesión firmado (itsdangerous). Se envía además como cookie HttpOnly `prodia_session`.
             * @example InVzZXJfaWQiOiAxfQ.ZkV4Sg.abc123
             */
            access_token: string;
            /**
             * Token Type
             * @description Tipo de token
             * @default bearer
             * @example bearer
             */
            token_type: string;
        };
        /**
         * LogoutResponse
         * @description Respuesta de POST /auth/logout.
         * @example {
         *       "message": "Sesión cerrada"
         *     }
         */
        LogoutResponse: {
            /**
             * Message
             * @description Confirmación de cierre de sesión
             * @example Sesión cerrada
             */
            message: string;
        };
        /**
         * MeResponse
         * @description Respuesta de GET /auth/me — usuario actual + permisos.
         */
        MeResponse: {
            /** @description Datos del usuario autenticado */
            user: components["schemas"]["UserOut"];
            /** @description Permisos efectivos (grupo + individuales) */
            permissions: components["schemas"]["UserPermissionsOut"];
        };
        /** PermissionGroupOut */
        PermissionGroupOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Is Admin */
            is_admin: boolean;
        };
        /**
         * SessionTimeoutOut
         * @description Respuesta de GET /auth/session-timeout — solo el valor vigente.
         *
         *     De solo lectura para cualquier usuario autenticado; la necesita el modal
         *     de inactividad del frontend para saber cuánto esperar antes de avisar.
         */
        SessionTimeoutOut: {
            /**
             * Session Timeout Minutes
             * @description Minutos de inactividad antes de que la sesión expire
             * @example 30
             */
            session_timeout_minutes: number;
        };
        /**
         * UserOut
         * @description Representación pública de un usuario (sin datos sensibles).
         */
        UserOut: {
            /**
             * Id
             * @description ID interno del usuario
             * @example 1
             */
            id: number;
            /**
             * Username
             * @description Usuario de red (sin dominio)
             * @example jguerrero
             */
            username: string;
            /**
             * Email
             * @description Correo corporativo
             * @example jguerrero@ecopetrol.com.co
             */
            email: string;
            /**
             * Full Name
             * @description Nombre completo
             * @example Javier Guerrero
             */
            full_name?: string | null;
            /**
             * Is Admin
             * @description Tiene privilegios de administrador
             */
            is_admin: boolean;
            /**
             * Is Active
             * @description Cuenta habilitada en la aplicación
             */
            is_active: boolean;
            /** @description Grupo de permisos asignado */
            group?: components["schemas"]["PermissionGroupOut"] | null;
            /**
             * Last Login At
             * @description Último login exitoso (ISO UTC)
             * @example 2026-05-06T14:30:00Z
             */
            last_login_at?: string | null;
            /**
             * Created At
             * @description Fecha de creación (ISO UTC)
             * @example 2026-01-15T08:00:00Z
             */
            created_at: string;
            /**
             * Updated At
             * @description Última modificación (ISO UTC)
             * @example 2026-05-06T14:30:00Z
             */
            updated_at: string;
        };
        /**
         * UserPermissionsOut
         * @description Permisos consolidados de un usuario (grupo + individuales).
         */
        UserPermissionsOut: {
            /**
             * Campos
             * @description Campos autorizados
             */
            campos?: string[];
            /**
             * Sections
             * @description Secciones autorizadas
             */
            sections?: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Credenciales inválidas, usuario inactivo o no registrado en `app_users` */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Error interno del servidor */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Servidor LDAP no disponible o timeout de conexión */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
            /** @description No autenticado — cookie ausente o inválida */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error interno del servidor */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description No autenticado — cookie ausente, inválida o sesión expirada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error interno del servidor */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    session_timeout_api_v1_auth_session_timeout_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionTimeoutOut"];
                };
            };
            /** @description No autenticado — cookie ausente, inválida o sesión expirada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    my_permissions_api_v1_permissions_my_permissions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPermissionsOut"];
                };
            };
            /** @description No autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
